[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "protdesign"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "licenseref-proprietary"
keywords = []
authors = [
  { name = "Thomas Hopf", email = "thomas.hopf@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["numpy", "pandas", "torch", "loguru", "biotite", "biopython", "dnachisel", "scikit-learn", "numba"]

[project.optional-dependencies]
evmutation2 = ["picasso_model"]
esm2 = ["transformers"]
umap = ["umap-learn"]

[project.urls]
Documentation = "https://github.com/thomashopf/protdesign#readme"
Issues = "https://github.com/thomashopf/protdesign/issues"
Source = "https://github.com/thomashopf/protdesign"

[tool.hatch.version]
path = "src/protdesign/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/protdesign tests}"

[tool.coverage.run]
source_pkgs = ["protdesign", "tests"]
branch = true
parallel = true
omit = [
  "src/protdesign/__about__.py",
]

[tool.coverage.paths]
protdesign = ["src/protdesign", "*/protdesign/src/protdesign"]
tests = ["tests", "*/protdesign/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
